In [3]:
import torch
torch.rand(20,1)

tensor([[0.5241],
        [0.3945],
        [0.6089],
        [0.9506],
        [0.9396],
        [0.5686],
        [0.6454],
        [0.0245],
        [0.9498],
        [0.3179],
        [0.4065],
        [0.6637],
        [0.7704],
        [0.2474],
        [0.9435],
        [0.9547],
        [0.8464],
        [0.7143],
        [0.6913],
        [0.4953]])

In [4]:
w = torch.tensor([1.], requires_grad=True)
x = torch.tensor([2.], requires_grad=True)

a = w + x
b = w + 1
y = a * b
# 反向传播要保存计算图
y.backward(retain_graph=True)
print(w.grad, x.grad)
y.backward()
print(w.grad, x.grad)   # 多次反向传播会使梯度累加

tensor([5.]) tensor([2.])
tensor([10.]) tensor([4.])


In [5]:
import numpy as np

n = np.random.rand(5)
print(n)

[0.01678521 0.47503081 0.13469822 0.0167481  0.43953131]


In [7]:
t = torch.tensor(n)
print(t.ge(0.5).float())

tensor([0., 0., 0., 0., 0.])
