In [1]:
import torch
torch.manual_seed(1)

In [2]:
# cat直接拼接
t = torch.ones((2,3))
t_0 = torch.cat([t,t], dim=0)
t_1 = torch.cat([t,t,t], dim=1)
print("t_0:{}".format(t_0))
print("t_0 shape:{}".format(t_0.shape))
print("t_1:{}".format(t_1))
print("t_1 shape:{}".format(t_1.shape))

t_0:tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
t_0 shape:torch.Size([4, 3])
t_1:tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])
t_1 shape:torch.Size([2, 9])


In [3]:
# stack扩维拼接
t = torch.ones((2,3))
t_stack = torch.stack([t,t,t], dim=0)
print("t_stack:{}".format(t_stack))
print("t_stack shape:{}".format(t_stack.shape))

t_stack:tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
t_stack shape:torch.Size([3, 2, 3])


In [4]:
# chunk均分为n块
a = torch.ones((2, 7))
list_of_tensors = torch.chunk(a, dim=1, chunks=3)
for idx, t in enumerate(list_of_tensors):
    print("第{}个张量:{}, shape is {}".format(idx+1, t, t.shape))

第1个张量:tensor([[1., 1., 1.],
        [1., 1., 1.]]), shape is torch.Size([2, 3])
第2个张量:tensor([[1., 1., 1.],
        [1., 1., 1.]]), shape is torch.Size([2, 3])
第3个张量:tensor([[1.],
        [1.]]), shape is torch.Size([2, 1])


In [4]:
# split按指定规则分割
a = torch.ones((2, 5))
list_of_tensors = torch.split(a, [2,1,2], dim=1)
for idx, t in enumerate(list_of_tensors):
    print("第{}个张量:{}, shape is {}".format(idx+1, t, t.shape))

第1个张量:tensor([[1., 1.],
        [1., 1.]]), shape is torch.Size([2, 2])
第2个张量:tensor([[1.],
        [1.]]), shape is torch.Size([2, 1])
第3个张量:tensor([[1., 1.],
        [1., 1.]]), shape is torch.Size([2, 2])


In [6]:
# index_select选择tensor中的某几行或列
t = torch.randint(0, 9, size=(3,3))
idx = torch.tensor([0,2], dtype=torch.long)
t_select = torch.index_select(t, dim=1, index=idx)
print("t:\n{}\n".format(t))
print("t_select:\n{}\n".format(t_select))

t:
tensor([[0, 2, 3],
        [1, 8, 4],
        [0, 3, 6]])

t_select:
tensor([[0, 3],
        [1, 4],
        [0, 6]])



In [7]:
# masked_select获取tensor中满足mask条件
t = torch.randint(0, 9, size=(3,3))
mask = t.le(5)
t_select = torch.masked_select(t, mask)
print("t:\n{}\n mask:\n{}\n t_sel:\n{}".format(t, mask, t_select))

t:
tensor([[0, 2, 3],
        [1, 8, 4],
        [0, 3, 6]])
 mask:
tensor([[ True,  True,  True],
        [ True, False,  True],
        [ True,  True, False]])
 t_sel:
tensor([0, 2, 3, 1, 4, 0, 3])


In [9]:
# reshape改变原tensor的形状
t = torch.randperm(8)
t_reshape = torch.reshape(t, (-1,2,2))
print("t:{}\n t_reshape:{}\n".format(t, t_reshape))
t[0] = 1024
print("t:{}\nt_reshape:{}".format(t, t_reshape))
print("t.data内存地址:{}".format(id(t.data)))
print(("t_reshape.data内存地址:{}").format(id(t_reshape.data)))


t:tensor([7, 0, 3, 6, 1, 5, 2, 4])
 t_reshape:tensor([[[7, 0],
         [3, 6]],

        [[1, 5],
         [2, 4]]])

t:tensor([1024,    0,    3,    6,    1,    5,    2,    4])
t_reshape:tensor([[[1024,    0],
         [   3,    6]],

        [[   1,    5],
         [   2,    4]]])
t.data内存地址:2121002189752
t_reshape.data内存地址:2121002189752


In [7]:
t = torch.randperm(16)
t_view = t.view(-1, 2,2,2)
print(f"{t} \n{t_view}")
print(f"{id(t)} \n{id(t_view)}")
t[0] = 1024
print(f"{t}\n{t_view}")
print(f"{id(t)}\n{id(t_view)}")

tensor([ 8,  2, 13, 15,  6,  3,  9, 14, 11,  4,  7,  5,  0, 12, 10,  1]) 
tensor([[[[ 8,  2],
          [13, 15]],

         [[ 6,  3],
          [ 9, 14]]],


        [[[11,  4],
          [ 7,  5]],

         [[ 0, 12],
          [10,  1]]]])
2337146075880 
2337142570664
tensor([1024,    2,   13,   15,    6,    3,    9,   14,   11,    4,    7,    5,
           0,   12,   10,    1])
tensor([[[[1024,    2],
          [  13,   15]],

         [[   6,    3],
          [   9,   14]]],


        [[[  11,    4],
          [   7,    5]],

         [[   0,   12],
          [  10,    1]]]])
2337146075880
2337142570664


In [10]:
# transpose对指定的两个维度进行转置
t = torch.rand((2,3,4))
t_transpose = torch.transpose(t, dim0=1, dim1=2)
print("t:{}\nt_transpose:{}".format(t, t_transpose))
print("t shape:{}\n t_transpose shape:{}".format(t.shape, t_transpose.shape))


t:tensor([[[0.2676, 0.9906, 0.2885, 0.8750],
         [0.5059, 0.2366, 0.7570, 0.2346],
         [0.6471, 0.3556, 0.4452, 0.0193]],

        [[0.2616, 0.7713, 0.3785, 0.9980],
         [0.9008, 0.4766, 0.1663, 0.8045],
         [0.6552, 0.1768, 0.8248, 0.8036]]])
t_transpose:tensor([[[0.2676, 0.5059, 0.6471],
         [0.9906, 0.2366, 0.3556],
         [0.2885, 0.7570, 0.4452],
         [0.8750, 0.2346, 0.0193]],

        [[0.2616, 0.9008, 0.6552],
         [0.7713, 0.4766, 0.1768],
         [0.3785, 0.1663, 0.8248],
         [0.9980, 0.8045, 0.8036]]])
t shape:torch.Size([2, 3, 4])
 t_transpose shape:torch.Size([2, 4, 3])


In [11]:
# squeeze压缩tensor中为1的维度,实现降维
t = torch.rand((1,2,3,1))
t_sq = torch.squeeze(t)
t_0 = torch.squeeze(t, dim=0)
t_1 = torch.squeeze(t, dim=1)
print(t.shape)
print(t_sq.shape)
print(t_0.shape)
print(t_1.shape) 

torch.Size([1, 2, 3, 1])
torch.Size([2, 3])
torch.Size([2, 3, 1])
torch.Size([1, 2, 3, 1])


In [15]:
# add实现两个维度相同的tensor相加
t_0 = torch.randn((3,3), dtype=torch.float)
t_1 = torch.ones_like(t_0)
t_add = torch.add(t_0, t_1)
print("t_0:\n{}\nt_1:\n{}\nt_add:\n{}".format(t_0, t_1, t_add))

t_0:
tensor([[-0.0179,  0.1280, -0.5552],
        [-0.4575, -1.9599, -1.1242],
        [-1.5599,  1.4003,  0.2963]])
t_1:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
t_add:
tensor([[ 0.9821,  1.1280,  0.4448],
        [ 0.5425, -0.9599, -0.1242],
        [-0.5599,  2.4003,  1.2963]])
