In [1]:
import torch
import numpy as np
torch.manual_seed(1)

In [6]:
# 通过torch.tensor创建张量
arr = np.ones((3,4))
print(arr.dtype)
t = torch.tensor(arr)
print(t)

float64
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [3]:
# 通过torch.from_numpy创建张量
arr = np.array([[1,2,3],[4,5,6]])
t = torch.from_numpy(arr)
print("修改tensor")
t[0,0] = -1
print("numpy array:", arr)
print("tensor:", t)

修改tensor
numpy array: [[-1  2  3]
 [ 4  5  6]]
tensor: tensor([[-1,  2,  3],
        [ 4,  5,  6]], dtype=torch.int32)


In [7]:
# 通过torch.zeros创建全0张量
out_t = torch.tensor([1])
print(id(out_t))
out_t = torch.zeros((3,3))
print(t, "\n", out_t)
print(id(t), id(out_t))

2095491491784
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) 
 tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
2095491491784 2095491491784


In [5]:
# 通过torch.full创建全1张量
t = torch.full((3,3), 1)
print(t)

RuntimeError: Providing a bool or integral fill value without setting the optional `dtype` or `out` arguments is currently unsupported. In PyTorch 1.7, when `dtype` and `out` are not set a bool fill value will return a tensor of torch.bool dtype, and an integral fill value will return a tensor of torch.long dtype.

In [8]:
# 通过torch.arange创建等差数列张量
t = torch.arange(2,10,2)
print(t)

tensor([2, 4, 6, 8])


In [9]:
# 通过torch.linspace创建均分数列张量
t = torch.linspace(2,10,6)
print(t)

tensor([ 2.0000,  3.6000,  5.2000,  6.8000,  8.4000, 10.0000])


In [10]:
# 通过torch.normal创建正态分布张量
mean = torch.arange(1,5,dtype=torch.float)
std = 1
t_normal = torch.normal(mean,std)
print("mean:{}, std:{}".format(mean, std))
print(t_normal)

mean:tensor([1., 2., 3., 4.]), std:1
tensor([1.6614, 2.2669, 3.0617, 4.6213])
