In [1]:
import torch
import numpy as np
torch.manual_seed(1)

In [3]:
# 通过torch.tensor创建张量
arr = np.ones((3,4))
print(arr.dtype)
t = torch.tensor(arr)
print(t)

float64
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [4]:
# 通过torch.from_numpy创建张量
arr = np.array([[1,2,3],[4,5,6]])
t = torch.from_numpy(arr)
print("修改tensor")
t[0,0] = -1
print("numpy array:", arr)
print("tensor:", t)

修改tensor
numpy array: [[-1  2  3]
 [ 4  5  6]]
tensor: tensor([[-1,  2,  3],
        [ 4,  5,  6]])


In [5]:
# 通过torch.zeros创建全0张量
out_t = torch.tensor([1])

t = torch.zeros((3,3), out=out_t)
print(t, "\n", out_t)
print(id(t), id(out_t))

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) 
 tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
140633469414768 140633469414768


In [6]:
# 通过torch.full创建全1张量
t = torch.full((3,3), 1)
print(t)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


../aten/src/ATen/native/TensorFactories.cpp:361: UserWarning: Deprecation warning: In a future PyTorch release torch.full will no longer return tensors of floating dtype by default. Instead, a bool fill_value will return a tensor of torch.bool dtype, and an integral fill_value will return a tensor of torch.long dtype. Set the optional `dtype` or `out` arguments to suppress this warning.


In [7]:
# 通过torch.arange创建等差数列张量
t = torch.arange(2,10,2)
print(t)

tensor([2, 4, 6, 8])


In [8]:
# 通过torch.linspace创建均分数列张量
t = torch.linspace(2,10,6)
print(t)

tensor([ 2.0000,  3.6000,  5.2000,  6.8000,  8.4000, 10.0000])


In [11]:
# 通过torch.normal创建正态分布张量
mean = torch.arange(1,5,dtype=torch.float)
std = 1
t_normal = torch.normal(mean,std)
print("mean:{}, std:{}".format(mean, std))
print(t_normal)

mean:tensor([1., 2., 3., 4.]), std:1
tensor([0.4369, 1.1077, 2.9417, 3.8045])
